# Generated by Django 4.2.17 on 2025-09-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MA60Minutes",
            fields=[
                ("log_dt", models.DateTimeField(primary_key=True, serialize=False)),
                ("market", models.CharField(max_length=45)),
                ("ma_10", models.FloatField()),
                ("ma_20", models.FloatField()),
                ("ma_34", models.FloatField()),
                ("ma_100", models.FloatField()),
                ("ma_200", models.FloatField()),
                ("ma_400", models.FloatField()),
                ("ma_800", models.FloatField()),
                ("golden_cross_10_34", models.IntegerField()),
                ("dead_cross_10_34", models.IntegerField()),
                ("created_at", models.TimeField()),
            ],
            options={
                "db_table": "tb_ma_60_minutes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MADays",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("market", models.CharField(max_length=45)),
                ("ma_10", models.FloatField()),
                ("ma_20", models.FloatField()),
                ("ma_34", models.FloatField()),
                ("ma_100", models.FloatField()),
                ("ma_200", models.FloatField()),
                ("ma_400", models.FloatField()),
                ("ma_800", models.FloatField()),
                ("golden_cross_10_34", models.IntegerField()),
                ("dead_cross_10_34", models.IntegerField()),
                ("created_at", models.TimeField()),
            ],
            options={
                "db_table": "tb_ma_days",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                ("log_dt", models.DateTimeField(primary_key=True, serialize=False)),
                ("market", models.CharField(max_length=45)),
                ("price", models.FloatField()),
            ],
            options={
                "db_table": "tb_market",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketDay",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("market", models.CharField(max_length=45)),
                ("opening_price", models.FloatField()),
                ("trade_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("volume", models.FloatField()),
                ("amount", models.FloatField()),
            ],
            options={
                "db_table": "tb_market_day",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarketHour",
            fields=[
                ("log_dt", models.DateTimeField(primary_key=True, serialize=False)),
                ("market", models.CharField(max_length=45)),
                ("opening_price", models.FloatField()),
                ("trade_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("volume", models.FloatField()),
                ("amount", models.FloatField()),
            ],
            options={
                "db_table": "tb_market_hour",
                "managed": False,
            },
        ),
    ]
