# Generated by Django 4.2.17 on 2025-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bithumb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "tb_market_info",
                "managed": False,
            },
        ),
    ]
