# Generated by Django 3.1 on 2021-05-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('game_idx', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('home_name', models.CharField(blank=True, max_length=3, null=True)),
                ('away_name', models.CharField(blank=True, max_length=3, null=True)),
                ('stadium', models.CharField(blank=True, max_length=2, null=True)),
                ('end', models.CharField(blank=True, max_length=4, null=True)),
                ('etc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'game_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PitcherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('po', models.IntegerField()),
                ('inn', models.FloatField(blank=True, null=True)),
                ('tbf', models.IntegerField(blank=True, null=True)),
                ('np', models.IntegerField(blank=True, null=True)),
                ('ab', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('tbb', models.IntegerField(blank=True, null=True)),
                ('so', models.IntegerField(blank=True, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('er', models.IntegerField(blank=True, null=True)),
                ('fip', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitcher_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunGraphData',
            fields=[
                ('team_game_idx', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('team_num', models.IntegerField(blank=True, null=True)),
                ('game_num', models.IntegerField(blank=True, null=True)),
                ('run_1', models.FloatField(blank=True, null=True)),
                ('run_5', models.FloatField(blank=True, null=True)),
                ('run_20', models.FloatField(blank=True, null=True)),
                ('rp_fip_5', models.FloatField(blank=True, null=True)),
                ('rp_fip_20', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'run_graph_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamGameInfo',
            fields=[
                ('team_game_idx', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('team_num', models.IntegerField(blank=True, null=True)),
                ('foe_num', models.IntegerField(blank=True, null=True)),
                ('game_num', models.IntegerField(blank=True, null=True)),
                ('home_away', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'team_game_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('team_num', models.IntegerField()),
                ('team_name', models.CharField(blank=True, max_length=3, null=True)),
                ('stadium', models.CharField(blank=True, max_length=2, null=True)),
                ('total_game_num', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('lose', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayGameInfo',
            fields=[
                ('game_idx', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('home_name', models.CharField(blank=True, max_length=3, null=True)),
                ('away_name', models.CharField(blank=True, max_length=3, null=True)),
                ('stadium', models.CharField(blank=True, max_length=2, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('etc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'today_game_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayLineUp',
            fields=[
                ('team_game_idx', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('bo', models.CharField(blank=True, max_length=10, null=True)),
                ('po', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'today_lineup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayTeamGameInfo',
            fields=[
                ('team_game_idx', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('team_num', models.IntegerField(blank=True, null=True)),
                ('foe_num', models.IntegerField(blank=True, null=True)),
                ('game_num', models.IntegerField(blank=True, null=True)),
                ('home_away', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'today_team_game_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatterRecord',
            fields=[
                ('team_game_idx', models.OneToOneField(db_column='team_game_idx', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baseball.teamgameinfo')),
                ('bo', models.IntegerField()),
                ('po', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('b1', models.IntegerField(blank=True, null=True)),
                ('b2', models.IntegerField(blank=True, null=True)),
                ('b3', models.IntegerField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('bb', models.IntegerField(blank=True, null=True)),
                ('hbp', models.IntegerField(blank=True, null=True)),
                ('ibb', models.IntegerField(blank=True, null=True)),
                ('sac', models.IntegerField(blank=True, null=True)),
                ('sf', models.IntegerField(blank=True, null=True)),
                ('so', models.IntegerField(blank=True, null=True)),
                ('go', models.IntegerField(blank=True, null=True)),
                ('fo', models.IntegerField(blank=True, null=True)),
                ('gidp', models.IntegerField(blank=True, null=True)),
                ('etc', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('tbb', models.IntegerField(blank=True, null=True)),
                ('ab', models.IntegerField(blank=True, null=True)),
                ('pa', models.IntegerField(blank=True, null=True)),
                ('xr', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batter_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('team_game_idx', models.OneToOneField(db_column='team_game_idx', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baseball.teamgameinfo')),
                ('result', models.CharField(blank=True, max_length=4, null=True)),
                ('x1', models.CharField(blank=True, max_length=2, null=True)),
                ('x2', models.CharField(blank=True, max_length=2, null=True)),
                ('x3', models.CharField(blank=True, max_length=2, null=True)),
                ('x4', models.CharField(blank=True, max_length=2, null=True)),
                ('x5', models.CharField(blank=True, max_length=2, null=True)),
                ('x6', models.CharField(blank=True, max_length=2, null=True)),
                ('x7', models.CharField(blank=True, max_length=2, null=True)),
                ('x8', models.CharField(blank=True, max_length=2, null=True)),
                ('x9', models.CharField(blank=True, max_length=2, null=True)),
                ('x10', models.CharField(blank=True, max_length=2, null=True)),
                ('x11', models.CharField(blank=True, max_length=2, null=True)),
                ('x12', models.CharField(blank=True, max_length=2, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('e', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score_record',
                'managed': False,
            },
        ),
    ]
